import {
  AirVent,
  Anchor,
  Antenna,
  Battery,
  BatteryCharging,
  Blocks,
  Bolt,
  Boxes,
  Brush,
  Cable,
  Camera,
  Car,
  Cctv,
  CircuitBoard,
  Cpu,
  Drill,
  Fan,
  Flashlight,
  Gamepad2,
  Gem,
  Hammer,
  HardDrive,
  HardHat,
  Headphones,
  Home,
  Keyboard,
  Lamp,
  Laptop,
  Lightbulb,
  type LucideIcon,
  MemoryStick,
  Microwave,
  Monitor,
  Mouse,
  Package,
  Paintbrush,
  Plug,
  PlugZap,
  Power,
  Printer,
  Radio,
  Refrigerator,
  Router,
  Ruler,
  SatelliteDish,
  ShoppingBasket,
  Smartphone,
  Speaker,
  Sun,
  SunMedium,
  Tablet,
  Thermometer,
  ToggleRight,
  Tv,
  Usb,
  Utensils,
  WashingMachine,
  Watch,
  Wind,
  Wrench,
  Zap,
} from "lucide-react";

/** Curated icon set the admin can pick from for each category. */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  package: Package,
  boxes: Boxes,
  basket: ShoppingBasket,
  // Electronics
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  monitor: Monitor,
  tv: Tv,
  headphones: Headphones,
  speaker: Speaker,
  camera: Camera,
  cctv: Cctv,
  printer: Printer,
  keyboard: Keyboard,
  mouse: Mouse,
  gamepad: Gamepad2,
  watch: Watch,
  radio: Radio,
  router: Router,
  antenna: Antenna,
  satellite: SatelliteDish,
  usb: Usb,
  harddrive: HardDrive,
  memory: MemoryStick,
  cpu: Cpu,
  circuitboard: CircuitBoard,
  // Electrical
  plug: Plug,
  plugzap: PlugZap,
  cable: Cable,
  zap: Zap,
  bolt: Bolt,
  power: Power,
  switch: ToggleRight,
  lightbulb: Lightbulb,
  lamp: Lamp,
  flashlight: Flashlight,
  battery: Battery,
  batterycharging: BatteryCharging,
  thermometer: Thermometer,
  // Solar & cooling
  sun: Sun,
  sunmedium: SunMedium,
  fan: Fan,
  wind: Wind,
  airvent: AirVent,
  // Home appliances
  refrigerator: Refrigerator,
  washingmachine: WashingMachine,
  microwave: Microwave,
  utensils: Utensils,
  // Construction & tools
  hammer: Hammer,
  wrench: Wrench,
  drill: Drill,
  hardhat: HardHat,
  blocks: Blocks,
  ruler: Ruler,
  paintbrush: Paintbrush,
  brush: Brush,
  home: Home,
  car: Car,
  anchor: Anchor,
  gem: Gem,
};

export const CATEGORY_ICON_KEYS = Object.keys(CATEGORY_ICONS);


export function CategoryIcon({
  icon,
  imageUrl,
  fallback,
  className = "",
}: {
  icon?: string | null;
  imageUrl?: string | null;
  fallback?: string;
  className?: string;
}) {
  if (imageUrl) {
    return <img src={imageUrl} alt="" className={`h-full w-full object-cover ${className}`} />;
  }
  const Icon = icon ? CATEGORY_ICONS[icon] : undefined;
  if (Icon) return <Icon className={`size-1/2 text-primary ${className}`} />;
  return <span className={`text-lg font-bold text-primary ${className}`}>{fallback ?? "•"}</span>;
}
